### ISSUE TITLE
ssl.SSLCertVerficiationError (issue with urllib3 library)

### ISSUE THREAD

**Issue by evelyn9191** [rossumai/elisctl#64]
The command ‘queue list’ fails with SSL Certificate Verification error when tried on the workspace 12911.

![urllib](https://user-images.githubusercontent.com/43633560/59099010-3d309c00-8922-11e9-9926-aaa2485431a3.jpg)

**Comment by KPilnacek** [comment]
It seems that `elisctl` is being used from behind some proxy that has a certificate not present among generally trusted certificates.

At first, please try that  direct interaction with our API works using `curl` command (for more information please see https://api.elis.rossum.ai/docs/#getting-started):
```shell
curl https://api.elis.rossum.ai/v1
```

In order to investigate the problem, please include information about the certificate chain. Run the following command and paste the result in here:
```shell
openssl s_client -showcerts -servername api.elis.rossum.ai -connect api.elis.rossum.ai:443
```

### how to solve missing certificate
The library used for communication between ELIS and `elisctl` is `requests` . So, the environment in which is `elisctl` running could be set to trust that certificate  (using environment variable `REQUESTS_CA_BUNDLE`, for more details see https://2.python-requests.org//en/master/user/advanced/#ssl-cert-verification).

**Comment by KPilnacek** [comment]
The problem might be as welled solved by specifying the proxy server address. One can do it using environment variable `HTTP_PROXY` (more details on https://2.python-requests.org//en/master/user/advanced/#proxies).
